CREATE OR REPLACE PROCEDURE SALES_DEV.COMMON.GET_CLOUD_AND_REGION()
RETURNS TABLE (CLOUD_PROVIDER VARCHAR, REGION_NAME VARCHAR)
LANGUAGE SQL
AS
DECLARE
  res RESULTSET;
BEGIN
  SHOW REGIONS LIKE '%';
  LET current_reg VARCHAR := (SELECT CURRENT_REGION());
  res := (
    SELECT "cloud" AS CLOUD_PROVIDER, "region" AS REGION_NAME
    FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
    WHERE "snowflake_region" = :current_reg
  );
  RETURN TABLE(res);
END;

CALL SALES_DEV.COMMON.GET_CLOUD_AND_REGION();